platform:
  - x86
  - x64

image: Previous Visual Studio 2013
os: unstable

environment:
  nodejs_version: "6.1"

branches:
  only:
    - master

skip_commits:
  message: /\[ci skip\]/

pull_requests:
  do_not_increment_build_number: true

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version $env:PLATFORM
  - node --version
  - npm --version
  - set npm_config_arch=%PLATFORM:x86=ia32%
  - npm install --progress false --depth 0
  - npm prune

build: off

test_script:
  - npm run test-ci
  - npm run package

before_deploy:
  - ps: Get-ChildItem dist\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
  provider: S3
  access_key_id:
    secure: xsHB6zN4IRGJy9uUocU3+6/nZPa408ARYut11Wg30CA=
  secret_access_key:
    secure: 8L4sC5l97dY13Jnv/6Gd8Fe//FpnOuMQWu7st2LNLRhX4LjQ9uSLfObqRT0HsBqw
  bucket:
    secure: a/ijSslVXIxT1KRgwK6oWBJiOYD2DS5KCC5JpEDtXaU=
  set_public: true
  folder: mozilla/tofino/builds
