platform:
  - x86

os: Previous Visual Studio 2015

environment:
  nodejs_version: "6.3"

skip_commits:
  message: /\[ci skip\]/

branches:
  except:
    - /^greenkeeper-.*$/

pull_requests:
  do_not_increment_build_number: true

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version $env:PLATFORM
  - node --version
  - npm --version
  - set npm_config_arch=%PLATFORM:x86=ia32%
  - npm prune
  - npm install --progress false --depth 0
  - npm install --progress false --depth 0

build: off

test_script:
  - npm run test-ci
  - npm run package

before_deploy:
  - ps: Get-ChildItem dist\RELEASES | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem dist\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem dist\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem dist\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
  - provider: S3
    access_key_id:
      secure: xsHB6zN4IRGJy9uUocU3+6/nZPa408ARYut11Wg30CA=
    secret_access_key:
      secure: 8L4sC5l97dY13Jnv/6Gd8Fe//FpnOuMQWu7st2LNLRhX4LjQ9uSLfObqRT0HsBqw
    bucket:
      secure: a/ijSslVXIxT1KRgwK6oWBJiOYD2DS5KCC5JpEDtXaU=
    set_public: true
    folder: mozilla/tofino/builds/$(appveyor_repo_branch)
    artifact: /^.*\.(zip|exe)$/
  - provider: GitHub
    description: 'Draft release'
    draft: true
    auth_token:
      secure: hJqkl2Amid9oaQZO9z0jedpQ3lNObygSTGPHDqOE+EEtnqQa0DkRDVJ3/i8i1YYg
    artifact: /^(RELEASES|.*\.(nupkg|exe))$/
    force_update: true
    on:
      appveyor_repo_tag: true
