platform:
  - x86
  - x64

image: Visual Studio 2013
os: unstable

environment:
  nodejs_version: "5.10"

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

cache:
  - node_modules
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version $env:PLATFORM
  - node --version
  - npm --version
  - set npm_config_arch=%PLATFORM:x86=ia32%
  - npm install --progress false --depth 0

build: off

test_script:
  - npm test
  - npm run package
